// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/theguarantors/tiger/entities"
)

// PolicyRepository is an autogenerated mock type for the PolicyRepository type
type PolicyRepository struct {
	mock.Mock
}

type PolicyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PolicyRepository) EXPECT() *PolicyRepository_Expecter {
	return &PolicyRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, id
func (_m *PolicyRepository) Get(ctx context.Context, id string) (*entities.Policy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Policy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Policy); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PolicyRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PolicyRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PolicyRepository_Expecter) Get(ctx interface{}, id interface{}) *PolicyRepository_Get_Call {
	return &PolicyRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *PolicyRepository_Get_Call) Run(run func(ctx context.Context, id string)) *PolicyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PolicyRepository_Get_Call) Return(_a0 *entities.Policy, _a1 error) *PolicyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PolicyRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*entities.Policy, error)) *PolicyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewPolicyRepository creates a new instance of PolicyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyRepository {
	mock := &PolicyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
