// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "github.com/theguarantors/tiger/entities"
)

// PolicyApp is an autogenerated mock type for the PolicyApp type
type PolicyApp struct {
	mock.Mock
}

type PolicyApp_Expecter struct {
	mock *mock.Mock
}

func (_m *PolicyApp) EXPECT() *PolicyApp_Expecter {
	return &PolicyApp_Expecter{mock: &_m.Mock}
}

// GetPolicy provides a mock function with given fields: ctx, id
func (_m *PolicyApp) GetPolicy(ctx context.Context, id string) (*entities.Policy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 *entities.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Policy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Policy); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PolicyApp_GetPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicy'
type PolicyApp_GetPolicy_Call struct {
	*mock.Call
}

// GetPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PolicyApp_Expecter) GetPolicy(ctx interface{}, id interface{}) *PolicyApp_GetPolicy_Call {
	return &PolicyApp_GetPolicy_Call{Call: _e.mock.On("GetPolicy", ctx, id)}
}

func (_c *PolicyApp_GetPolicy_Call) Run(run func(ctx context.Context, id string)) *PolicyApp_GetPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PolicyApp_GetPolicy_Call) Return(_a0 *entities.Policy, _a1 error) *PolicyApp_GetPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PolicyApp_GetPolicy_Call) RunAndReturn(run func(context.Context, string) (*entities.Policy, error)) *PolicyApp_GetPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewPolicyApp creates a new instance of PolicyApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyApp {
	mock := &PolicyApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
