// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
)

// S3Client is an autogenerated mock type for the S3Client type
type S3Client struct {
	mock.Mock
}

type S3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *S3Client) EXPECT() *S3Client_Expecter {
	return &S3Client_Expecter{mock: &_m.Mock}
}

// Options provides a mock function with no fields
func (_m *S3Client) Options() s3.Options {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 s3.Options
	if rf, ok := ret.Get(0).(func() s3.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(s3.Options)
	}

	return r0
}

// S3Client_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type S3Client_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
func (_e *S3Client_Expecter) Options() *S3Client_Options_Call {
	return &S3Client_Options_Call{Call: _e.mock.On("Options")}
}

func (_c *S3Client_Options_Call) Run(run func()) *S3Client_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *S3Client_Options_Call) Return(_a0 s3.Options) *S3Client_Options_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *S3Client_Options_Call) RunAndReturn(run func() s3.Options) *S3Client_Options_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function with given fields: ctx, params, optFns
func (_m *S3Client) PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// S3Client_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type S3Client_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.PutObjectInput
//   - optFns ...func(*s3.Options)
func (_e *S3Client_Expecter) PutObject(ctx interface{}, params interface{}, optFns ...interface{}) *S3Client_PutObject_Call {
	return &S3Client_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *S3Client_PutObject_Call) Run(run func(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options))) *S3Client_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*s3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*s3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*s3.PutObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *S3Client_PutObject_Call) Return(_a0 *s3.PutObjectOutput, _a1 error) *S3Client_PutObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *S3Client_PutObject_Call) RunAndReturn(run func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *S3Client_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewS3Client creates a new instance of S3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Client {
	mock := &S3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
